#!/usr/bin/env python3
"""
Fill in the plain-English paper summaries that scripts/fetch_papers.py leaves blank.

fetch_papers.py deliberately calls no model — it just records each paper's
abstract in _data/papers_cache.yml with an empty summary. This script is the
other half: `pending` reports what still needs writing, and `apply` writes the
summaries back into the cache and into _data/papers.yml (which is what Jekyll
actually renders).

The summaries themselves are written by Claude Code, on the Claude subscription
— there is no API key anywhere in this pipeline. See .claude/commands/refresh-summaries.md.

Usage:
  scripts/summaries.py pending              # YAML of papers needing a summary
  scripts/summaries.py pending --count      # just the number, for scripting
  scripts/summaries.py apply summaries.yml  # bibcode -> summary mapping
  cat summaries.yml | scripts/summaries.py apply -
  scripts/summaries.py sync                 # re-sync papers.yml from the cache
"""

from __future__ import annotations

import argparse
import pathlib
import sys
from typing import Any

import yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA_FILE = ROOT / "_data" / "papers.yml"
CACHE_FILE = ROOT / "_data" / "papers_cache.yml"

DATA_HEADER = "# Auto-generated by scripts/fetch_papers.py — do not edit by hand.\n"
CACHE_HEADER = (
    "# Auto-generated by scripts/fetch_papers.py — do not edit by hand.\n"
    "# Durable cache of summaries, abstracts and figure paths, keyed by bibcode.\n"
    "# Never pruned: entries outlive rotation out of papers.yml.\n"
)

# A summary is two sentences on a card; anything much longer is a sign the
# model wrote an abstract instead of a summary.
MAX_SUMMARY_CHARS = 600


def load_yaml(path: pathlib.Path, default: Any) -> Any:
    if not path.exists():
        return default
    data = yaml.safe_load(path.read_text())
    return default if data is None else data


def load_papers() -> list[dict[str, Any]]:
    data = load_yaml(DATA_FILE, [])
    return data if isinstance(data, list) else []


def load_cache() -> dict[str, dict[str, Any]]:
    data = load_yaml(CACHE_FILE, {})
    return data if isinstance(data, dict) else {}


def save_cache(cache: dict[str, dict[str, Any]]) -> None:
    CACHE_FILE.write_text(
        CACHE_HEADER
        + yaml.safe_dump(cache, sort_keys=True, allow_unicode=True, width=100)
    )


def save_papers(papers: list[dict[str, Any]]) -> None:
    DATA_FILE.write_text(
        DATA_HEADER
        + yaml.safe_dump(papers, sort_keys=False, allow_unicode=True, width=100)
    )


def sync_papers_from_cache(cache: dict[str, dict[str, Any]]) -> int:
    """Copy cached summaries into papers.yml. Returns the number changed."""
    papers = load_papers()
    changed = 0
    for paper in papers:
        cached = cache.get(paper.get("bibcode"), {})
        summary = cached.get("summary")
        if summary and paper.get("summary") != summary:
            paper["summary"] = summary
            changed += 1
    if changed:
        save_papers(papers)
    return changed


def cmd_pending(args: argparse.Namespace) -> int:
    cache = load_cache()
    # Only papers currently on the front page matter — the rest aren't rendered.
    wanted = [p.get("bibcode") for p in load_papers()] if not args.all else list(cache)

    pending = []
    for bib in wanted:
        entry = cache.get(bib) or {}
        if entry.get("summary"):
            continue
        abstract = entry.get("abstract")
        if not abstract:
            # No abstract cached (ADS had none, or the paper predates the
            # cache) — nothing to summarize from, so don't ask for one.
            continue
        pending.append({
            "bibcode": bib,
            "title": entry.get("title", ""),
            "abstract": abstract,
        })

    if args.count:
        print(len(pending))
        return 0

    if not pending:
        print("# All rendered papers have summaries.")
        return 0

    sys.stdout.write(yaml.safe_dump(pending, sort_keys=False, allow_unicode=True, width=100))
    return 0


def cmd_apply(args: argparse.Namespace) -> int:
    raw = sys.stdin.read() if args.file == "-" else pathlib.Path(args.file).read_text()
    incoming = yaml.safe_load(raw)
    if not isinstance(incoming, dict):
        print("error: expected a YAML mapping of bibcode -> summary", file=sys.stderr)
        return 1

    cache = load_cache()
    applied = 0
    for bib, summary in incoming.items():
        if not isinstance(summary, str) or not summary.strip():
            print(f"skip {bib}: empty summary", file=sys.stderr)
            continue
        summary = " ".join(summary.split())
        if len(summary) > MAX_SUMMARY_CHARS:
            print(
                f"skip {bib}: summary is {len(summary)} chars "
                f"(limit {MAX_SUMMARY_CHARS}) — shorten it and retry",
                file=sys.stderr,
            )
            continue
        if bib not in cache:
            print(f"skip {bib}: not a known bibcode", file=sys.stderr)
            continue
        cache[bib]["summary"] = summary
        applied += 1

    if not applied:
        print("Nothing applied.", file=sys.stderr)
        return 1

    save_cache(cache)
    synced = sync_papers_from_cache(cache)
    print(f"Applied {applied} summaries to the cache; updated {synced} entries in papers.yml.")
    return 0


def cmd_sync(_args: argparse.Namespace) -> int:
    synced = sync_papers_from_cache(load_cache())
    print(f"Updated {synced} entries in papers.yml from the cache.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    sub = parser.add_subparsers(dest="command", required=True)

    p_pending = sub.add_parser("pending", help="list papers that still need a summary")
    p_pending.add_argument("--count", action="store_true", help="print only the count")
    p_pending.add_argument("--all", action="store_true",
                           help="include cached papers not currently on the front page")
    p_pending.set_defaults(func=cmd_pending)

    p_apply = sub.add_parser("apply", help="write summaries into the cache and papers.yml")
    p_apply.add_argument("file", help="YAML file of bibcode -> summary, or - for stdin")
    p_apply.set_defaults(func=cmd_apply)

    p_sync = sub.add_parser("sync", help="re-sync papers.yml summaries from the cache")
    p_sync.set_defaults(func=cmd_sync)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
